config/routes.rb
Rails.application.routes.draw do
  resources :bloggers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogger.rb
class Blogger < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :set_blogger, only: [:show, :edit, :update, :destroy]

  # GET /bloggers
  # GET /bloggers.json
  def index
    @bloggers = Blogger.all
  end

  # GET /bloggers/1
  # GET /bloggers/1.json
  def show
  end

  # GET /bloggers/new
  def new
    @blogger = Blogger.new
  end

  # GET /bloggers/1/edit
  def edit
  end

  # POST /bloggers
  # POST /bloggers.json
  def create
    @blogger = Blogger.new(blogger_params)

    respond_to do |format|
      if @blogger.save
        format.html { redirect_to @blogger, notice: 'Blogger was successfully created.' }
        format.json { render :show, status: :created, location: @blogger }
      else
        format.html { render :new }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggers/1
  # PATCH/PUT /bloggers/1.json
  def update
    respond_to do |format|
      if @blogger.update(blogger_params)
        format.html { redirect_to @blogger, notice: 'Blogger was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogger }
      else
        format.html { render :edit }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloggers/1
  # DELETE /bloggers/1.json
  def destroy
    @blogger.destroy
    respond_to do |format|
      format.html { redirect_to bloggers_url, notice: 'Blogger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogger
      @blogger = Blogger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogger_params
      params.require(:blogger).permit(:name, :emailaddr, :rank)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/views/bloggers/_form.html.erb
<%= form_with(model: blogger, local: true) do |form| %>
  <% if blogger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogger.errors.count, "error") %> prohibited this blogger from being saved:</h2>

      <ul>
      <% blogger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :emailaddr %>
    <%= form.text_area :emailaddr %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.number_field :rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Editing Blogger</h1>

<%= render 'form', blogger: @blogger %>

<%= link_to 'Show', @blogger %> |
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bloggers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Emailaddr</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggers.each do |blogger| %>
      <tr>
        <td><%= blogger.name %></td>
        <td><%= blogger.emailaddr %></td>
        <td><%= blogger.rank %></td>
        <td><%= link_to 'Show', blogger %></td>
        <td><%= link_to 'Edit', edit_blogger_path(blogger) %></td>
        <td><%= link_to 'Destroy', blogger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogger', new_blogger_path %>

app/views/bloggers/new.html.erb
<h1>New Blogger</h1>

<%= render 'form', blogger: @blogger %>

<%= link_to 'Back', bloggers_path %>

app/views/bloggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blogger.name %>
</p>

<p>
  <strong>Emailaddr:</strong>
  <%= @blogger.emailaddr %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @blogger.rank %>
</p>

<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>